name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Adjust permissions on target directory
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no deploy@prophesierc.site "sudo chown -R deploy:deploy /var/www/prophesierc.site/prophesierc/age-calculator-app-main && sudo chmod -R 755 /var/www/prophesierc.site/prophesierc/age-calculator-app-main"

      - name: Clean up target directory
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no deploy@prophesierc.site "rm -rf /var/www/prophesierc.site/prophesierc/age-calculator-app-main/*"

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          source: "." 
          target: "/var/www/prophesierc.site/prophesierc/age-calculator-app-main/"
          host: prophesierc.site
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          strip_components: 1
          rm: true
          overwrite: true

      - name: Set permissions
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no deploy@prophesierc.site "sudo chown -R deploy:deploy /var/www/prophesierc.site/prophesierc/age-calculator-app-main && sudo chmod -R 755 /var/www/prophesierc.site/prophesierc/age-calculator-app-main"

      - name: Clean up SSH Key
        run: rm key.pem
